# Generated by Django 2.0.1 on 2018-01-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='slug',
            new_name='description',
        ),
    ]
