# Generated by Django 2.0.1 on 2018-01-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180123_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
    ]
