# Generated by Django 2.0.1 on 2018-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
