# Generated by Django 2.0.1 on 2018-01-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articles_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
    ]
